"use strict";
let car = 'sabaru';
console.log("is car=='sabaru?'predict True");
console.log(car == 'sabaru');
console.log("is car != 'honda city' predict true");
console.log(car != 'honda city');
console.log("is car=='sabaru?'predict False");
console.log(car == 'Sabaru');
console.log("is car=='SABARU?'predict False");
console.log(car == 'SABARU');
console.log("is car.length==6? Predic True");
console.log(car.length == 6);
console.log("is car.length!=10? Predic True");
console.log(car.length != 10);
console.log('is 10 > 5 ? Predict False');
console.log(10 > 45);
console.log('is 3 <= 2 ? Predict False');
console.log(3 <= 2);
console.log('is 63 >= 82 ? Predict False');
console.log(63 >= 82);
console.log("is car== 'sabaru'? predict True");
console.log(car == 'sabaru');
console.log("is car.length==6 ? predict True");
console.log(car.length == 6);
